---
abstract: 'Microsoft Translator backend for I22r::Translate'
author:
  - "Marty O'Brien <mob@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: I22r-Translate-Microsoft
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  HTML::Entities: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  I22r::Translate: 0.92
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
  URL::Encode: 0
  XML::XPath: 0
version: 0.93
