---
abstract: 'Microsoft Translator backend for I22r::Translate'
author:
  - "Marty O'Brien, C<< <mob at cpan.org> >>"
build_requires:
  # --- Module::Install::Admin::Makefile section:

realclean purge ::
	$(RM_F) $(DISTVNAME).tar$(SUFFIX)
	$(RM_F) MANIFEST.bak _build
	$(PERL) "-Ilib" "-MModule::Install::Admin" -e "remove_meta()"
	$(RM_RF) inc

reset :: purge

upload :: test dist
	cpan-upload -verbose $(DISTVNAME).tar$(SUFFIX)

grok ::
	perldoc Module::Install

distsign ::
	cpansign -s

# --- Module::Install::AutoInstall section:

config :: installdeps
	$(NOECHO) $(NOOP)

checkdeps ::
	$(PERL) Makefile.PL --checkdeps

installdeps ::
	$(NOECHO) $(NOOP)

installdeps_notest ::
	$(NOECHO) $(NOOP)

upgradedeps ::
	$(PERL) Makefile.PL --config= --upgradedeps=

upgradedeps_notest ::
	$(PERL) Makefile.PL --config= --upgradedeps=

listdeps ::
	@$(PERL) -le "print for @ARGV" 

listalldeps ::
	@$(PERL) -le "print for @ARGV" 

: 0
  Encode: 0
  ExtUtils::MakeMaker: 6.36
  HTML::Entities: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  I22r::Translate: 0.92
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
  URL::Encode: 0
  XML::XPath: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: I22r-Translate-Microsoft
no_index:
  directory:
    - inc
    - t
requires:
  # --- Module::Install::Admin::Makefile section:

realclean purge ::
	$(RM_F) $(DISTVNAME).tar$(SUFFIX)
	$(RM_F) MANIFEST.bak _build
	$(PERL) "-Ilib" "-MModule::Install::Admin" -e "remove_meta()"
	$(RM_RF) inc

reset :: purge

upload :: test dist
	cpan-upload -verbose $(DISTVNAME).tar$(SUFFIX)

grok ::
	perldoc Module::Install

distsign ::
	cpansign -s

# --- Module::Install::AutoInstall section:

config :: installdeps
	$(NOECHO) $(NOOP)

checkdeps ::
	$(PERL) Makefile.PL --checkdeps

installdeps ::
	$(NOECHO) $(NOOP)

installdeps_notest ::
	$(NOECHO) $(NOOP)

upgradedeps ::
	$(PERL) Makefile.PL --config= --upgradedeps=

upgradedeps_notest ::
	$(PERL) Makefile.PL --config= --upgradedeps=

listdeps ::
	@$(PERL) -le "print for @ARGV" 

listalldeps ::
	@$(PERL) -le "print for @ARGV" 

: 0
  Encode: 0
  HTML::Entities: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  I22r::Translate: 0.92
  JSON: 0
  LWP::UserAgent: 0
  URL::Encode: 0
  XML::XPath: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.94
